config/routes.rb
MtApp::Application.routes.draw do

  devise_for :users
  resources :projects do 
    resources :comments, only: [:create, :destroy] 
    resources :tasks do
      resources :assignments
    end
    
    resources :discussions do
      resources :comments, only: [:create, :destroy] 
    end

  end

  root 'projects#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
belongs_to :user

has_many :tasks
has_many :users, through: :tasks, source: :user

has_many :discussions
has_many :users, through: :discussions, source: :user

has_many :comments, as: :commentable
has_many :commenters, through: :comments, source: :user

after_initialize :set_defaults
  #Scope that orders projects by hit count
  scope :order_by_hits, -> { order("hit_counter DESC") } #doesnt expect pipes
  scope :x_most_recent, lambda { |max| order("updated_at DESC").limit(max) }
  scope :test, Proc.new { |max| order("created_at DESC").limit(max) }
  scope :x_by_votes, lambda { |max| order("score DESC").limit(max) }

private
def set_defaults
  self.hit_counter ||= 0
end


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

  @projects_recent = Project.order("updated_at DESC")

  recent_ids = []
  @projects_recent.each {|x| recent_ids << x.id }
  @projects_by_hits = Project.order_by_hits
  Rails.logger.info '>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>'
  Rails.logger.info recent_ids

  @projects_left_over = @projects_by_hits.select { |x| !recent_ids.include?(x.id) }


  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @task = Task.new
    @discussion = @project.discussions
    @comment=Comment.new
    @project.hit_counter += 1
    @project.save
    
    Rails.logger.info ">>>>>>>>>>>>>>"
    Rails.logger.info @project.tasks
    Rails.logger.info @project.discussions
    # Rails.logger.info @discussion.comments
    
    #@task = Task.all
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    #@project = Project.new(project_params)
    @project = current_user.projects.new project_params
      if @project.save
        redirect_to @project, notice: 'Project was successfully created.' 
      else
        redirect_to @project, alert: "Sorry Something Went Wrong"
      end
 
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :client, :body, :status, :category, :hit_counter, :user_id)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_discussions.html.erb
  <% @project.discussions.each do |discussion| %>

      <strong>Title:</strong>
      <%= discussion.title %>
    </p>
    <p>
      <strong>User:</strong>
      <%= discussion.user.email %>
    </p>
    <p>
      <strong>body:</strong>
      <%= discussion.body %>
    </p>
      <%= link_to 'Destroy',project_discussion_path(@project, discussion), method: :delete, data: { confirm: 'Are you sure?' } %>
<hr>
<h3> Discussion Comments </h3>

  <% discussion.comments.each do |comment| %>
  <p>
    <strong>body:</strong>
    <%= comment.body %>
  </p>
  <p>
    <strong>comment by:</strong>
    <%= comment.user.email %>
  </p>
  <p>
    <strong>date posted:</strong>
    <%= comment.created_at %>
  </p>

  <%= link_to 'Destroy',project_discussion_comment_path(@project, discussion, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %> 

  <div class="form-group">  
  <%= form_for [@project, discussion, @comment] do |f| %>
    <%= f.label :body %><br>
    <%= f.text_area :body , class: "form-control" %>

    <%= f.submit "Submit Comment", class: "btn btn-default" %>
  <% end %>  </div>

    <% end %>

app/views/projects/_form.html.erb
  <div class="form-group">

  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%= form_for @project do |f| %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, class: "form-control"%>
  </div>

  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category, class: "form-control" %>
  </div>
 
  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-default"  %>
  </div>
<% end %>
</div>

app/views/projects/_tasks.html.erb
  <h2> Completed Tasks </h2>
  <% @project.tasks.each do |task| %>
    <% if task.completed %>

      <strong>Name:</strong>
      <%= task.name %>
      <strong>due_date:</strong>
      <%= task.due_date %>
      <br><strong>completed:</strong>
      YES  <%= link_to 'Mark as Incomplete', edit_project_task_path(@project, task) %>
      </p>
      <p>
      <strong>body:</strong>
      <%= task.body %>
      </p>
      <%= link_to 'Destroy',project_task_path(@project, task), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
   <% end %>       

<h2> Incomplete Tasks </h2>
  <% @project.tasks.each do |task| %>
        <% if !task.completed %>
        <p>  
        <strong>Name:</strong>
        <%= task.name %>
        <strong>due_date:</strong>
        <%= task.due_date %>
        <br><strong>completed:</strong>
          No  <%= link_to 'Mark as Complete', edit_project_task_path(@project, task) %>
        </p>
        <p>
        <strong>body:</strong>
        <%= task.body %>
        </p>
        <%= link_to 'Destroy',project_task_path(@project, task), method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
    <% end %> 



<h3> Add a Task </h3>
<p><%#= link_to 'Add Task', new_project_task_path %>
  <%= form_for [@project, @task] do |f| %>
  
  <div class="form-field">
    <%= f.label :name %><br>
    <%= f.text_field :name , class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br>
    <%= f.date_field :due_date , class: "form-control"%>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, class: "form-control" %>
  </div>
      <ul>
      <% hidden_field_tag "task[user_ids][]", nil %>
      <% User.all.each do |c| %>
      
        <li><%= check_box_tag "task[user_ids][]", c.id, @task.assignments.include?(c.id), id: dom_id(c) %>
        <%= label_tag dom_id(c), c.email %></li>
      
      <%end%>
    <div class="actions">
      <%= f.submit %>
   </div>

   <%end%>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
      <div class="buffer">
        <h2 class="navbar-fixed-top">THE REPOSITORY
          <%= link_to 'CREATE NEW REPO', new_project_path, class: "btn btn-primary back-lit-btn pull-right" %>
        </h2>
      </div>

<div class="container">
  <div class="row">
    <div class="col-xs-10 col-sm-10 col-md-10"> 
      <br><br><br>
    </div>
  </div>
</div>



  <div class="row">
    <div class="col-xs-6 col-sm-6 col-md-6">
        <h3>Most Recent Repositories</h3>
        <% @projects_recent.each do |project| %>
            
            <!-- <div class="well"> -->

          <h4><i class="fa fa-book fa-2x"></i><%= project.title %></h4>
          <br><%= project.updated_at %> | views: <%= project.hit_counter %> |
          <br><strong>Created By:</strong> <%= project.user.email %> 
          <br><strong>Category:</strong> <%= project.category %>
          <br><%= project.body.truncate(140) %>
          <br><%= link_to 'Show', project, class: "btn btn-info back-lit-btn" %>  
          <%= link_to 'Edit', edit_project_path(project), class: "btn btn-info back-lit-btn", remote: true %>  
          <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } ,class: "btn btn-danger back-lit-btn" %> 
     <!-- </div> -->
        <% end %>
    </div>
    
    <div class="col-xs-6 col-sm-6 col-md-6"><div class="well">
        <h3>Most Popular Repositories</h3>
        <% @projects_by_hits.each do |project| %>

          <p>|Views: <%= project.hit_counter %> |<span class="glyphicon glyphicon-book"></span>
          <%= link_to project.title, project %>
           </p>
          <hr>
        <% end %>
    </div>
    </div>

  </div>



<br>

app/views/projects/new.html.erb
<h1>New Repository</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
    <h2>
              <strong></strong>
              <%= @project.title %>
    </h2>
    <p>
              <strong>Client:</strong>
              <%= @project.client %>
    </p>
    <p>
              <strong>Body:</strong>
              <%= @project.body %>
    </p>
    <p>
              <strong>Status:</strong>
              <%= @project.status %>
    </p>
    <p>
              <strong>Category:</strong>
              <%= @project.category %>
    </p>
    <p>
              <strong>Views:</strong>
              <%= @project.hit_counter %>
    </p>
    
    <%= link_to 'Edit', edit_project_path(@project) %>
    <%if can? :manage, @project %>
    | <%= link_to 'Back', projects_path %> |
      <%= link_to 'Destroy', @project , method: :delete, data: { confirm: 'Are you sure?' } %> |
    <%end%>
  
  <hr><h3>Poject Comments</h3>
  <%= render "comments/comments_form" %>
  <br>

  <hr>   
  <div class="well">
    <h2>Discussions <%= link_to 'Add a Discussion', new_project_discussion_path(@project), class: "btn btn-primary pull-right" %></h2>
          <%= render "discussions" %>
  </div>

  
    